### PR TITLE
Update to 1.1.4

### PR DESCRIPTION
**Pull request by XxParkerGamesxX**
## Tested it?
- [ ] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by xISRAPILx** [comment]
Tested? @XxParkerGamesxX

**Comment by XxParkerGamesxX** [comment]
Yes i have tested it

**Comment by xISRAPILx** [comment]
Thank's! @XxParkerGamesxX

**Comment by XxParkerGamesxX** [comment]
Np could i be added to this software i worked for alot of them but the owners gave up on them

**Pull request merged**
